### ISSUE TITLE
Error in codelist-mapping.xml causing validator problems

### ISSUE THREAD

**Issue by andylolz** [IATI/pyIATI#224] opened 2017-11-07 16:49 UTC
There’s a bug with codelists mappings that’s fixed in this PR:
https://github.com/IATI/IATI-Codelists/pull/109

The same bug is repeated here:
https://github.com/IATI/pyIATI/blob/f3c9b54dd3fb6d5e6fc48b3329e6b9a9682d1318/iati/resources/standard/202/codelist-mapping.xml#L60

So `iati.default.codelist_mapping()` loads that… And that’s used by the validator:
https://github.com/IATI/pyIATI/blob/b454bdae51bf706fcb6e46a7c0a0a4b3b27d8e09/iati/validator.py#L287

So when I run `iati.validator.is_valid(dataset, schema)` I hit an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".ve/src/pyiati/iati/validator.py", line 693, in is_valid
    return _correct_codelist_values(dataset, schema) and _conforms_with_ruleset(dataset, schema)
  File ".ve/src/pyiati/iati/validator.py", line 500, in _correct_codelist_values
    error_log = _check_codelist_values(dataset, schema)
  File ".ve/src/pyiati/iati/validator.py", line 341, in _check_codelist_values
    error_log.extend(_check_codes(dataset, codelist))
  File ".ve/src/pyiati/iati/validator.py", line 307, in _check_codes
    parents_to_check = dataset.xml_tree.xpath(parent_el_xpath)
  File "src/lxml/etree.pyx", line 2289, in lxml.etree._ElementTree.xpath (src/lxml/etree.c:69770)
  File "src/lxml/xpath.pxi", line 359, in lxml.etree.XPathDocumentEvaluator.__call__ (src/lxml/etree.c:179350)
  File "src/lxml/xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/etree.c:177714)
lxml.etree.XPathEvalError: Invalid expression
```

Fixing the bug in the codelist mapping appears to fix the problem.

**Comment by hayfield** [comment] 2017-11-07 18:08
This would likely have been caught with more detailed checks on the SSOT test data.

Slight ramble of my thoughts on some tests that should be added... The SSOT test data is designed for verifying that the Schema permits various types of data. This means that full validation cannot necessarily be undertaken. Many placeholder values are, however, made up of `x`s - it should be possible to filter error logs of this kind of error, leaving only information that is useful, actionable and relevant.

Do you have a minimal test case Dataset that causes this error? (am assuming a populated default 2.02 Schema)

**Comment by andylolz** [comment] 2017-11-07 21:44
> Do you have a minimal test case Dataset that causes this error? (am assuming a populated default 2.02 Schema)

Yep, exactly – populated default schema and [test_data/202/valid_iati.xml](https://github.com/IATI/pyIATI/blob/9b74e511/iati/resources/test_data/202/valid_iati.xml) does the trick.

```python
from os.path import join
import iati


fn = join('iati', 'resources', 'test_data', '202', 'valid_iati.xml')
with open(fn) as fh:
    xml_str = fh.read()

schema = iati.default.activity_schema()
dataset = iati.Dataset(xml_str)

iati.validator.is_valid(dataset, schema)  # lxml.etree.XPathEvalError: Invalid expression
```

**Comment by hayfield** [comment] 2017-11-08 09:31
Looking in `test_validator.py`, there are tests against Schemas with each specific type of Codelist (complete, incomplete, vocabularies, Language), though nothing against a fully populated Schema - this looks like an oversight when adding populated default Schemas.

**Comment by hayfield** [comment] 2017-11-08 09:47
The XPath at the point of failure is: `//iati-activity/crs-add/crs-add/channel-code[@ext()]`.

This indicates that the problem is with the assumption that XPaths being checked by a mapping file refer to attributes, rather than text in an element.

This seems like a mis-implementation in the Standard (introduced at 2.02) - Codelists should refer to attribute values, *NOT* element text.

**Comment by andylolz** [comment] 2017-11-08 10:03
Github does not allow me to react to that with a 😢  so you will just have to imagine.

Right, yes. You are right. So there are maybe three things to fix, then:

 1. the duplicate `crs-add` typo, both in the 2.02 SSOT and [over here](https://github.com/IATI/pyIATI/blob/f3c9b54dd3fb6d5e6fc48b3329e6b9a9682d1318/iati/resources/standard/202/codelist-mapping.xml#L60)
 2. the issue with the standard that you mention (i.e. channel codes in the text of `crs-add/channel-code` rather than an attribute)
 3. pyIATI probably needs a workaround for (2) ?

**Comment by hayfield** [comment] 2017-11-08 10:33
> So there are maybe three things to fix

Yep

> 1. the duplicate crs-add typo, both in the 2.02 SSOT and over here

pyIATI simply has a copypaste of SSOT content, so at present it's a bug with the SSOT rather than pyIATI - the latter can be fixed once the former is.

> 2. the issue with the standard that you mention

I've started the internal process for determining how best to progress with this issue within the constraints of backwards-compatibility and upgrade-schedules.

> 3. pyIATI probably needs a workaround for (2) ?

Aye - will look to sort that out now.

**Comment by hayfield** [comment] 2017-11-08 12:15
1) and 3) are fixed in https://github.com/IATI/pyIATI/pull/229

**Comment by hayfield** [comment] 2018-02-21 08:42
In `0.3.0`.

**Closed by hayfield** 2018-02-21 08:42 UTC
Labels: awaiting-deployment, bug, codelists, validation
